---
engines:
  sonarscharp:
    base_dir: "Assets/Scripts"
  duplication:
    exclude_paths:
      - "Assets/TutorialInfo/**"
      - "Assets/Shared/**"
      - "Packages/**"
      - "ProjectSettings/**"
      - "UserSettings/**"
    config:
      languages:
        - "C#"
exclude_paths:
  - "Assets/TutorialInfo/**"
      - "Assets/Shared/**"
      - "Packages/**"
      - "ProjectSettings/**"
      - "UserSettings/**"
