name: Codacy Analysis CLI

on: 
  push:
    paths-ignore:
      - 'Assets/TutorialInfo/**'
      - 'Assets/Shared/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'UserSettings/**'
  pull-request:
    paths-ignore:
      - 'Assets/TutorialInfo/**'
      - 'Assets/Shared/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'UserSettings/**'

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
